server:
  port: 9527

spring:
  application:
    name: cloud-gateway
#########    新增gateway配置start
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_route # 路由的 ID ，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001  # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/getPaymentById/**  # 断言，路径相匹配的进行路由
        - id: payment_routh #payment_route # 路由的 ID ，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001  # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**  # 断言，路径相匹配的进行路由
#########    新增gateway配置end
eureka:
  instance:
    hostname: cloud-gateway-serivce
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka