server:
  port: 9527

spring:
  application:
    name: cloud-gateway
#########    新增gateway配置start
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route # 路由的 ID,没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 需要注意的是uri的协议为lb，表示启用Gateway的负载均衡功能
          predicates:
            - Path=/payment/getPaymentById/**  # 断言，路径相匹配的进行路由
#            - After=2022-05-09T18:41:06.497+08:00[Asia/Shanghai]
#            - Cookie=username,gy
        - id: payment_routh #payment_route # 路由的 ID,没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 需要注意的是uri的协议为lb，表示启用Gateway的负载均衡功能
          predicates:
            - Path=/payment/lb/**  # 断言，路径相匹配的进行路由
            - Cookie=username,gy
#            - After=2022-05-09T18:41:06.497+08:00[Asia/Shanghai]
#########    新增gateway配置end
eureka:
  instance:
    hostname: cloud-gateway-serivce
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka