server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
#      connect-string: 127.0.0.1:2181 # 配置zookeeper服务器的连接
      connect-string: 39.105.228.254:2181 # 配置zookeeper服务器的连接